repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3  # Replace with the latest version
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi ]
      # Run the formatter
      - id: ruff-format
        types_or: [ python, pyi ]
  
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8  # Use the latest version
    hooks:
      - id: clang-format
        files: \.(c|cc|cpp|cxx|c\+\+|h|hh|hpp|hxx|h\+\+)$
        args: [-i]
