repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3  # Replace with the latest version
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi ]
      # Run the formatter
      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8  # Use the latest version
    hooks:
      - id: clang-format
        files: \.(c|cc|cpp|cxx|c\+\+|h|hh|hpp|hxx|h\+\+)$
        args: [-i]

  # Additional code quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Run unit tests to ensure they pass
  - repo: local
    hooks:
      - id: pytest
        name: Run unit tests
        entry: python -m pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        args: [tests/, -x, --tb=short, -q]
        stages: [pre-commit]

      - id: coverage-check
        name: Block push if coverage < 90%
        entry: bash scripts/check_coverage.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
