repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7  # Replace with the latest version
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi ]
      # Run the formatter
      - id: ruff-format
        types_or: [ python, pyi ]
